"""Generate README.txt for the report package."""

from datetime import datetime
from pathlib import Path
from typing import Optional


class ReadmeGenerator:
    """Generator pliku README."""

    TEMPLATE = """DataAnalysis Report Package
===========================

Client: {client_name}
Generated: {generated_at}
Run ID: {run_id}

Contents
--------
{file_list}

File Descriptions
-----------------
Report_Main.csv          - Main report with all KPIs (Section | Metric | Value format)
DQ_Summary.csv           - Data Quality summary metrics
DQ_MissingCritical.csv   - SKUs with missing critical data (dimensions, weight)
DQ_SuspectOutliers.csv   - SKUs with suspect values (potential outliers)
DQ_HighRiskBorderline.csv- SKUs close to carrier limits (within {borderline_mm}mm)
DQ_Masterdata_Duplicates.csv - Duplicate SKU entries
DQ_Masterdata_Conflicts.csv  - SKUs with conflicting values
DQ_SKU_Collisions.csv    - SKU collisions after normalization
DQ_ImputedSKUs.csv       - SKUs with imputed (estimated) values
Manifest.json            - File checksums (SHA256)

CSV Format
----------
- Separator: ;
- Encoding: UTF-8 with BOM
- Newline: CRLF (Windows)

Number Formatting
-----------------
- Volume (m3): 6 decimal places
- Weight (kg): 3 decimal places
- Percentages: 2 decimal places with % sign
- Rates (/hour, /day): 3 decimal places
- Counts: Integer, no thousand separators

---
Generated by DataAnalysis v{version}
"""

    def __init__(self) -> None:
        """Initialize the generator."""
        pass

    def generate(
        self,
        output_path: Path,
        files: list[Path],
        client_name: str = "",
        run_id: Optional[str] = None,
        borderline_mm: float = 2.0,
        version: str = "0.1.0",
    ) -> Path:
        """Generate README.txt.

        Args:
            output_path: Path to the README file
            files: List of files in the package
            client_name: Client name
            run_id: Run identifier
            borderline_mm: Borderline threshold in mm
            version: Application version

        Returns:
            Path to the generated README
        """
        # File list
        file_list = "\n".join(f"- {f.name}" for f in files if f.exists())

        content = self.TEMPLATE.format(
            client_name=client_name or "N/A",
            generated_at=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            run_id=run_id or datetime.now().strftime("%Y%m%d_%H%M%S"),
            file_list=file_list,
            borderline_mm=borderline_mm,
            version=version,
        )

        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(content)

        return output_path


def generate_readme(
    output_path: Path,
    files: list[Path],
    **kwargs,
) -> Path:
    """Helper function to generate README.

    Args:
        output_path: Path to the README file
        files: List of files
        **kwargs: Additional arguments

    Returns:
        Path to the generated README
    """
    generator = ReadmeGenerator()
    return generator.generate(output_path, files, **kwargs)
