"""Excel (xlsx) generator for the Data Quality report.

One workbook with a Summary sheet plus one sheet per DQ list — for both the
Masterdata side (DQ pipeline) and the Orders side (orders validation).
"""

from __future__ import annotations

import io
from datetime import datetime
from typing import Any

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

HEADER_FILL = PatternFill(start_color="374151", end_color="374151", fill_type="solid")
HEADER_FONT = Font(color="FFFFFF", bold=True, size=11)
SECTION_FILL = PatternFill(start_color="1d4ed8", end_color="1d4ed8", fill_type="solid")
SECTION_FONT = Font(color="FFFFFF", bold=True, size=11)
CENTER = Alignment(horizontal="center", vertical="center")


def _style_header(ws, row: int, n_cols: int) -> None:
    for col in range(1, n_cols + 1):
        c = ws.cell(row=row, column=col)
        c.fill = HEADER_FILL
        c.font = HEADER_FONT
        c.alignment = CENTER
    ws.row_dimensions[row].height = 22
    ws.freeze_panes = f"A{row + 1}"


def _style_section_row(ws, row: int, n_cols: int) -> None:
    for col in range(1, n_cols + 1):
        c = ws.cell(row=row, column=col)
        c.fill = SECTION_FILL
        c.font = SECTION_FONT


def _autosize(ws) -> None:
    for col_idx, col in enumerate(ws.columns, start=1):
        max_len = 0
        for cell in col:
            v = cell.value
            if v is not None:
                max_len = max(max_len, len(str(v)))
        ws.column_dimensions[get_column_letter(col_idx)].width = min(max_len + 2, 60)


def _generated_by(user: Any) -> str:
    if user is None:
        return "—"
    name = getattr(user, "name", None) or ""
    email = getattr(user, "email", None) or ""
    if name and email:
        return f"{name} <{email}>"
    return name or email or "—"


def _sheet_summary(wb: Workbook, run: Any, qr: dict, ovr: dict, user: Any) -> None:
    ws = wb.create_sheet("Summary", 0)
    ws.append(["Field", "Value"])
    _style_header(ws, 1, 2)

    ws.append(["Generated by", _generated_by(user)])
    ws.append(["Client", run.client_name or run.id])
    ws.append(["Generated at", datetime.now().strftime("%Y-%m-%d %H:%M")])

    # Masterdata
    if qr:
        ws.append([])
        section_row = ws.max_row + 1
        ws.append(["Masterdata data quality", ""])
        _style_section_row(ws, section_row, 2)
        pairs = [
            ("Total records", qr.get("total_records")),
            ("Overall score (%)", qr.get("overall_score")),
            ("Dimensions coverage (%)", qr.get("dimensions_coverage_pct")),
            ("Weight coverage (%)", qr.get("weight_coverage_pct")),
            ("Stock coverage (%)", qr.get("stock_coverage_pct")),
            ("Missing critical", qr.get("missing_critical_count")),
            ("Suspect outliers", qr.get("suspect_outliers_count")),
            ("High-risk borderline", qr.get("high_risk_borderline_count")),
            ("Duplicates", qr.get("duplicates_count")),
            ("Conflicts", qr.get("conflicts_count")),
            ("Imputed dimensions", qr.get("imputed_dimensions_count")),
            ("Imputed weight", qr.get("imputed_weight_count")),
        ]
        for k, v in pairs:
            ws.append([k, v])

    # Orders
    if ovr:
        ws.append([])
        section_row = ws.max_row + 1
        ws.append(["Orders data quality", ""])
        _style_section_row(ws, section_row, 2)
        pairs = [
            ("Total rows", ovr.get("total_rows")),
            ("Date from", ovr.get("date_from")),
            ("Date to", ovr.get("date_to")),
            ("Unique days", ovr.get("unique_days")),
            ("Calendar days in range", ovr.get("total_calendar_days")),
            ("Calendar coverage (%)", ovr.get("date_coverage_pct")),
            ("Date gap count", ovr.get("gap_count")),
            ("Max gap (days)", ovr.get("max_gap_days")),
            ("Has hourly data", "Yes" if ovr.get("has_hourly_data") else "No"),
            ("Missing SKUs", ovr.get("missing_sku_count")),
            ("Missing SKUs (%)", ovr.get("missing_sku_pct")),
            ("Qty null", ovr.get("qty_null_count")),
            ("Qty zero", ovr.get("qty_zero_count")),
            ("Qty negative", ovr.get("qty_negative_count")),
            ("Qty outliers", ovr.get("qty_outlier_count")),
            ("Qty outlier threshold", ovr.get("qty_outlier_threshold")),
            ("Orders SKUs not in masterdata", ovr.get("orders_skus_not_in_masterdata_count")),
            ("Masterdata SKUs not in orders", ovr.get("masterdata_skus_not_in_orders_count")),
        ]
        for k, v in pairs:
            ws.append([k, v])

    _autosize(ws)


def _sheet_rows(wb: Workbook, title: str, rows: list[dict], columns: list[str]) -> None:
    """Generic sheet writer for a list of dicts using the supplied column order."""
    ws = wb.create_sheet(title)
    ws.append(columns)
    _style_header(ws, 1, len(columns))
    for r in rows:
        ws.append([r.get(c) for c in columns])
    if not rows:
        ws.append(["(no rows)"] + [""] * (len(columns) - 1))
    _autosize(ws)


def _sheet_string_list(wb: Workbook, title: str, header: str, items: list[str], note: str | None = None) -> None:
    ws = wb.create_sheet(title)
    ws.append([header])
    _style_header(ws, 1, 1)
    for sku in items:
        ws.append([sku])
    if not items:
        ws.append(["(no entries)"])
    if note:
        ws.append([])
        ws.append([note])
    _autosize(ws)


def generate_dq_xlsx(run: Any, user: Any = None) -> bytes:
    """Build the multi-sheet DQ workbook for an analysis run.

    Sheets created depend on which data is present on the run:
        - Summary (always)
        - Masterdata - Missing Critical / Suspect Outliers / Borderline / Duplicates / Conflicts
          (only when ``run.quality_result`` exists)
        - Orders - Date Gaps / Unknown SKUs / Inactive SKUs
          (only when ``run.orders_validation_result`` exists)
    """
    qr = run.quality_result or {}
    ovr = run.orders_validation_result or {}

    if not qr and not ovr:
        raise ValueError("No data quality results available for this run.")

    wb = Workbook()
    default = wb.active
    if default is not None and default.title == "Sheet":
        wb.remove(default)

    _sheet_summary(wb, run, qr, ovr, user)

    # Masterdata sheets
    if qr:
        md_columns = ["sku", "field", "value", "details"]
        _sheet_rows(wb, "MD - Missing Critical", qr.get("missing_critical", []) or [], md_columns)
        _sheet_rows(wb, "MD - Suspect Outliers", qr.get("suspect_outliers", []) or [], md_columns)
        _sheet_rows(wb, "MD - Borderline", qr.get("high_risk_borderline", []) or [], md_columns)
        _sheet_rows(wb, "MD - Duplicates", qr.get("duplicates", []) or [], md_columns)
        _sheet_rows(wb, "MD - Conflicts", qr.get("conflicts", []) or [], md_columns)

    # Orders sheets
    if ovr:
        _sheet_rows(
            wb,
            "Orders - Date Gaps",
            ovr.get("gap_list", []) or [],
            ["from", "to", "days"],
        )
        unknown = ovr.get("orders_skus_not_in_masterdata", []) or []
        unknown_count = int(ovr.get("orders_skus_not_in_masterdata_count") or 0)
        unknown_note = (
            f"Truncated preview — full count: {unknown_count}"
            if unknown_count > len(unknown)
            else None
        )
        _sheet_string_list(wb, "Orders - Unknown SKUs", "sku", unknown, unknown_note)

        inactive = ovr.get("masterdata_skus_not_in_orders", []) or []
        inactive_count = int(ovr.get("masterdata_skus_not_in_orders_count") or 0)
        inactive_note = (
            f"Truncated preview — full count: {inactive_count}"
            if inactive_count > len(inactive)
            else None
        )
        _sheet_string_list(wb, "Orders - Inactive SKUs", "sku", inactive, inactive_note)

    buf = io.BytesIO()
    wb.save(buf)
    return buf.getvalue()
